collections_config:
  Pages:
    path: _pages
    glob:
    name: Pages
    singular_name:
    icon: sticky_note_2
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    view_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  Data:
    path: _data
    glob:
    name:
    singular_name:
    icon: database
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    view_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  Posts:
    path: _posts
    glob:
    name:
    singular_name:
    icon: edit_note
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    view_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  Camps:
    path: _camps
    glob:
    name:
    singular_name:
    icon: camping
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    view_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
  Events:
    path: _events
    glob:
    name:
    singular_name:
    icon: calendar_month
    url:
    disable_url: false
    include_developer_files:
    documentation:
    description:
    preview:
    sort:
    sort_options:
    view_options:
    _editables:
    _enabled_editors:
    _inputs:
    _select_data:
    _structures:
    add_options:
    create:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url:
    schemas:
    schema_key:
_enabled_editors:
  - data
  - content
  - visual
_inputs:
  title:
    type: text
    label: Title
    cascade: true
  description:
    type: textarea
    label: Description
    cascade: true
  image:
    type: image
    label: Featured Image
    cascade: true
  date:
    type: date
    label: Date
    cascade: true
  tags:
    type: multiselect
    label: Tags
    cascade: true
  featured:
    type: checkbox
    label: Featured Item
    cascade: true
  src:
    type: image
    cascade: true
  answer:
    type: html
    cascade: true
_select_data:
  colors:
    - Red
    - Green
    - Blue
  categories:
    - News
    - Updates
    - Events
_editables:
  block:
    allow_custom_markup: true
    remove_custom_markup: true
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    resize_style: cover
    right: text-right
    styles: /assets/css/style.css
    table: true
    underline: true
  content:
    allow_custom_markup: true
    remove_custom_markup: true
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    copyformatting: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: false
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    redo: true
    removeformat: true
    resize_style: cover
    right: text-right
    styles: /assets/css/style.css
    table: true
    underline: true
  image:
    expandable: true
    height: 300
    image_size_attributes: true
    mime_type:
    paths:
    resize_style: crop
    width: 400
  text:
    allow_custom_markup: true
    remove_custom_markup: true
    bold: true
    copyformatting: true
    italic: true
    link: true
    paths:
    redo:
    removeformat:
    strike:
    subscript:
    superscript:
    underline:
    undo:
timezone: Etc/UTC
_editor:
  default_path: /
uploads:
  path: uploads/:title/:year/:month/:day/:categories
