collections_config:
  Pages:
    path: _pages
    glob: null
    name: Pages
    singular_name: null
    icon: sticky_note_2
    url: null
    disable_url: false
    include_developer_files: null
    documentation: null
    description: null
    preview: null
    sort: null
    sort_options: null
    view_options: null
    _editables: null
    _enabled_editors: null
    _inputs: null
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas: null
    schema_key: null
  Data:
    path: _data
    glob: null
    name: null
    singular_name: null
    icon: database
    url: null
    disable_url: false
    include_developer_files: null
    documentation: null
    description: null
    preview: null
    sort: null
    sort_options: null
    view_options: null
    _editables: null
    _enabled_editors: null
    _inputs: null
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas: null
    schema_key: null
  Posts:
    path: _posts
    glob: null
    name: null
    singular_name: null
    icon: edit_note
    url: null
    disable_url: false
    include_developer_files: null
    documentation: null
    description: null
    preview: null
    sort: null
    sort_options: null
    view_options: null
    _editables: null
    _enabled_editors: null
    _inputs: null
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas: null
    schema_key: null
  Camps:
    path: _camps
    glob: null
    name: null
    singular_name: null
    icon: camping
    url: null
    disable_url: false
    include_developer_files: null
    documentation: null
    description: null
    preview: null
    sort: null
    sort_options: null
    view_options: null
    _editables: null
    _enabled_editors: null
    _inputs: null
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas: null
    schema_key: null
  Events:
    path: _events
    glob: null
    name: null
    singular_name: null
    icon: calendar_month
    url: null
    disable_url: false
    include_developer_files: null
    documentation: null
    description: null
    preview: null
    sort: null
    sort_options: null
    view_options: null
    _editables: null
    _enabled_editors: null
    _inputs: null
    _select_data: null
    _structures: null
    add_options: null
    create: null
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    new_preview_url: null
    schemas: null
    schema_key: null
_inputs:
  title:
    type: text
    label: Title
    cascade: true
  description:
    type: textarea
    label: Description
    cascade: true
  image:
    type: image
    label: Featured Image
    cascade: true
  date:
    type: date
    label: Date
    cascade: true
  tags:
    type: multiselect
    label: Tags
    cascade: true
  featured:
    type: checkbox
    label: Featured Item
    cascade: true
_select_data:
  colors:
    - Red
    - Green
    - Blue
  categories:
    - News
    - Updates
    - Events
timezone: Etc/UTC
_enabled_editors:
  - data
  - content
  - visual
_editables:
  block:
    allow_custom_markup: true
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: true
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    resize_style: cover
    right: text-right
    styles: /assets/css/style.css
    table: true
    underline: true
  content:
    allow_custom_markup: true
    remove_custom_markup: false
    blockquote: true
    bold: true
    bulletedlist: true
    center: text-center
    code: true
    copyformatting: true
    embed: true
    expandable: true
    format: p h1 h2 h3 h4 h5 h6 pre address div
    image: true
    image_size_attributes: false
    indent: true
    italic: true
    left: text-left
    link: true
    numberedlist: true
    redo: true
    removeformat: true
    resize_style: cover
    right: text-right
    styles: /assets/css/editor.css
    table: true
    underline: true
  image:
    expandable: null
    height: 300
    image_size_attributes: true
    mime_type: null
    paths: null
    resize_style: crop
    width: 400
_editor:
  default_path: /
uploads:
  path: 'uploads/:title/:year/:month/:day/:categories'
